// <file>
//     <copyright see="prj:///doc/copyright.txt"/>
//     <license see="prj:///doc/license.txt"/>
//     <owner name="David Srbecký" email="dsrbecky@gmail.com"/>
//     <version>$Revision: 2201 $</version>
// </file>

// This file is automatically generated - any changes will be lost

using System;

#pragma warning disable 1591

namespace PascalSharp.Internal.Debugger.Wrappers.CorDebug
{
    public partial class ICorDebugHeapValue2
	{
		
		private Interop.CorDebug.ICorDebugHeapValue2 wrappedObject;
		
		internal Interop.CorDebug.ICorDebugHeapValue2 WrappedObject
		{
			get
			{
				return this.wrappedObject;
			}
		}
		
		public ICorDebugHeapValue2(Interop.CorDebug.ICorDebugHeapValue2 wrappedObject)
		{
			this.wrappedObject = wrappedObject;
			ResourceManager.TrackCOMObject(wrappedObject, typeof(ICorDebugHeapValue2));
		}
		
		public static ICorDebugHeapValue2 Wrap(Interop.CorDebug.ICorDebugHeapValue2 objectToWrap)
		{
			if ((objectToWrap != null))
			{
				return new ICorDebugHeapValue2(objectToWrap);
			} else
			{
				return null;
			}
		}
		
		~ICorDebugHeapValue2()
		{
			object o = wrappedObject;
			wrappedObject = null;
			ResourceManager.ReleaseCOMObject(o, typeof(ICorDebugHeapValue2));
		}
		
		public bool Is<T>() where T: class
		{
			System.Reflection.ConstructorInfo ctor = typeof(T).GetConstructors()[0];
			System.Type paramType = ctor.GetParameters()[0].ParameterType;
			return paramType.IsInstanceOfType(this.WrappedObject);
		}
		
		public T As<T>() where T: class
		{
			try {
				return CastTo<T>();
			} catch {
				return null;
			}
		}
		
		public T CastTo<T>() where T: class
		{
			return (T)Activator.CreateInstance(typeof(T), this.WrappedObject);
		}
		
		public static bool operator ==(ICorDebugHeapValue2 o1, ICorDebugHeapValue2 o2)
		{
			return ((object)o1 == null && (object)o2 == null) ||
			       ((object)o1 != null && (object)o2 != null && o1.WrappedObject == o2.WrappedObject);
		}
		
		public static bool operator !=(ICorDebugHeapValue2 o1, ICorDebugHeapValue2 o2)
		{
			return !(o1 == o2);
		}
		
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}
		
		public override bool Equals(object o)
		{
			ICorDebugHeapValue2 casted = o as ICorDebugHeapValue2;
			return (casted != null) && (casted.WrappedObject == wrappedObject);
		}
		
		
		public ICorDebugHandleValue CreateHandle(CorDebugHandleType type)
		{
			ICorDebugHandleValue ppHandle;
			Interop.CorDebug.ICorDebugHandleValue out_ppHandle;
			this.WrappedObject.CreateHandle(((Interop.CorDebug.CorDebugHandleType)(type)), out out_ppHandle);
			ppHandle = ICorDebugHandleValue.Wrap(out_ppHandle);
			return ppHandle;
		}
	}
}

#pragma warning restore 1591
